### ISSUE TITLE
fix: show correct destination amount on swap

### ISSUE THREAD

**Issue by thomas779** [useloopso/loopso-swap#14]
Available from the `getFee()` available from the SDK. Make sure `isFungible` is of boolean type that checks what fee should be applied to each token type (fungible vs non-fungible). The fee should be called from the destination contract address the user has selected.

**Steps**
1. Call `getFee()` and store number on client-side 
2. Get the user inserted amount
3. Calculate fee by `amount - (amount * fee)`

Example: 100 USDT - (100 USDT * 0.005) = 99.5 USDT

**Intended outcome**
![image](https://github.com/useloopso/loopso-swap/assets/57649600/92181cfa-3283-4684-8541-7478438d4e79)

**Comment by dannxbt** [comment]
fixed and tested
