### ISSUE TITLE
fix: fetch list of tokens from connected provider

### ISSUE THREAD

**Issue by thomas779** [useloopso/loopso-swap#16]
**Problem**
Currently, assets are fetched from a `constants.ts` file (predefined list) in the code. This isn't great because it prevents the core ethos of our bridge "bridge any token". 

**Solution**
Fetch the list of assets from the user's connected provider so that the user can select from a list that is of interest to them. It's a massive UX improvement.

**Note**
- Only be able to fetch the contract address and the amount on their wallet. An 3rd party API may need to be called to fetch any relevant metadata (the ERC20 token icon, unless that is on the contract).
- Requires #10 to be implemented for non-fungibles

**Comment by dannxbt** [comment]
fixed !
