### ISSUE TITLE
fix: require src chain is selected before token selection

### ISSUE THREAD

**Issue by thomas779** [useloopso/loopso-swap#17]
**Introduction**
`Select Token` btn on the frontend shouldn’t be toggled unless it meets the following conditions:
1. A wallet is connected 
2. A src chain is connected

**Why?**
- We cannot fetch a list of assets (impl #16) if neither 1. or 2. are connected.
- We can prevent the user from inserting a larger number (e.g. user has 100 USDT in their wallet, so we block the user from inserting >100 USDT on the UI)

**Comment by dannweeeee** [comment]
done !
