### ISSUE TITLE
fix: prevent duplicate network selection 

### ISSUE THREAD

**Issue by thomas779** [useloopso/loopso-swap#18]
User can select the same network for their source and destination.

**Comment by dannxbt** [comment]
done with the logic, but a promise error kept happening:

Uncaught (in promise) Error: could not coalesce error (error={ "code": -32004, "message": "method not supported eth_newFilter" }, payload={ "id": 2, "jsonrpc": "2.0", "method": "eth_newFilter", "params": [ { "address": [ "0xa7a00a3d0a8023e5cf446cad412585260bec2d33" ], "topics": [ "0xe436066797d3bcdab647d36495d87e5dba7a58a6c132890edcc038d783a596c1" ] } ] }, code=UNKNOWN_ERROR, version=6.8.1)
    at makeError (webpack-internal:///(app-pages-browser)/./node_modules/ethers/lib.esm/utils/errors.js:137:21)
    at JsonRpcProvider.getRpcError (webpack-internal:///(app-pages-browser)/./node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:672:74)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:287:45)

**Comment by thomas779** [comment]
> done with the logic, but a promise error kept happening:
> 
> Uncaught (in promise) Error: could not coalesce error (error={ "code": -32004, "message": "method not supported eth_newFilter" }, payload={ "id": 2, "jsonrpc": "2.0", "method": "eth_newFilter", "params": [ { "address": [ "0xa7a00a3d0a8023e5cf446cad412585260bec2d33" ], "topics": [ "0xe436066797d3bcdab647d36495d87e5dba7a58a6c132890edcc038d783a596c1" ] } ] }, code=UNKNOWN_ERROR, version=6.8.1) at makeError (webpack-internal:///(app-pages-browser)/./node_modules/ethers/lib.esm/utils/errors.js:137:21) at JsonRpcProvider.getRpcError (webpack-internal:///(app-pages-browser)/./node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:672:74) at eval (webpack-internal:///(app-pages-browser)/./node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:287:45)

@dannweeeee  When does this error occur? e.g. when you bridge tokens? when you swap NFTs? etc

**Comment by dannxbt** [comment]
it is fixed now and tested!
